# Generated by Django 4.2.6 on 2023-11-01 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 31, 22, 24, 20, 267614)),
        ),
    ]
