# Generated by Django 4.2.6 on 2023-11-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
